# Generated by Django 2.1.8 on 2020-06-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg_mobile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('meid', models.CharField(max_length=32)),
                ('imei1', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=32)),
                ('seller', models.CharField(max_length=32)),
                ('sell_num_day', models.CharField(max_length=32)),
                ('sell_num_week', models.CharField(max_length=32)),
                ('sell_num_month', models.CharField(max_length=32)),
                ('sell_num_year', models.CharField(max_length=32)),
                ('sell_num_all', models.CharField(max_length=32)),
                ('data_num', models.DateField()),
            ],
        ),
    ]
